name: Pull Request Test

on:
  pull_request:
    # branches: [ "feature/**" ]
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - 'docs/**'


jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 1
  
    steps:
      - run: exit 1 # intentionally fail
      - uses: actions/checkout@v3